# Generated by Django 5.2.7 on 2025-10-01 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        help_text="Name of the healthcare provider", max_length=255
                    ),
                ),
                (
                    "appointment_time",
                    models.DateTimeField(
                        help_text="Scheduled date and time for the appointment"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        help_text="Email address of the client",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when appointment was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when appointment was last updated",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(
                        default=False, help_text="Payment status of the appointment"
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe PaymentIntent ID",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["-appointment_time"],
            },
        ),
    ]
